package com.threatatlas;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * The Dark Arts: Java Native Interface (JNI).
 * Bypasses network overhead by loading the compiled C++ engine directly into JVM memory.
 */
public class JniEmbedder implements AutoCloseable {

    private static final Logger log = LoggerFactory.getLogger(JniEmbedder.class);

    // This static block executes the moment the class is loaded by the JVM.
    // It looks for libthreat_engine_jni.so (Linux), .dylib (Mac), or .dll (Windows).
    static {
        try {
            System.loadLibrary("threat_engine_jni");
            log.info("[+] Successfully mapped C++ Threat Engine into JVM memory.");
        } catch (UnsatisfiedLinkError e) {
            log.error("[!] FATAL: Could not find the C++ shared library. " +
                      "Did you compile the C++ core with -shared and update your java.library.path?", e);
            throw e;
        }
    }

    // A pointer to the C++ memory address of the ONNX session.
    // If we don't hold this, C++ will try to reload the 80MB model for every single log chunk.
    private long nativeModelHandle;

    public JniEmbedder(String modelPath) {
        log.info("[*] Initializing Native ONNX Session from: {}", modelPath);
        this.nativeModelHandle = initializeNative(modelPath);
        if (this.nativeModelHandle == 0) {
            throw new RuntimeException("C++ failed to initialize the model. Check standard error.");
        }
    }

    // ==========================================
    // Native Method Signatures
    // (These map exactly to the C headers generated by the `javah` tool)
    // ==========================================
    private native long initializeNative(String modelPath);
    private native float[] generateEmbeddingNative(long handle, String text);
    private native void cleanupNative(long handle);

    /**
     * Takes a raw log string and asks the native C++ memory space to embed it.
     */
    public float[] embed(String text) {
        if (this.nativeModelHandle == 0) {
            throw new IllegalStateException("Cannot embed: Native model handle is null or closed.");
        }
        return generateEmbeddingNative(this.nativeModelHandle, text);
    }

    /**
     * JNI does NOT have garbage collection. 
     * If you don't call this, the C++ pointers will bleed memory until your server explodes.
     */
    @Override
    public void close() {
        if (this.nativeModelHandle != 0) {
            log.info("[*] Freeing C++ memory pointers...");
            cleanupNative(this.nativeModelHandle);
            this.nativeModelHandle = 0;
            log.info("[+] Native memory successfully cleared.");
        }
    }
}
