// cpp-core/src/grpc_server.cpp
#include "grpc_server.h"
#include "threat_engine.grpc.pb.h" // Generated by Protoc
#include <iostream>

namespace threatatlas {

class VectorComputeServiceImpl final : public VectorComputeService::Service {
private:
    std::shared_ptr<Embedder> embedder_;
    std::shared_ptr<FaissIndexManager> faiss_index_;

public:
    VectorComputeServiceImpl(std::shared_ptr<Embedder> emb, std::shared_ptr<FaissIndexManager> idx)
        : embedder_(emb), faiss_index_(idx) {}

    grpc::Status GenerateEmbedding(grpc::ServerContext* context, const LogChunk* request,
                                   VectorResponse* reply) override {
        
        std::cout << "[gRPC] Received chunk: " << request->source_id() << std::endl;
        
        try {
            std::vector<float> vec = embedder_->generate_embedding(request->raw_text());
            
            reply->set_source_id(request->source_id());
            for (float val : vec) {
                reply->add_embeddings(val);
            }
            return grpc::Status::OK;
        } catch (const std::exception& e) {
            return grpc::Status(grpc::StatusCode::INTERNAL, e.what());
        }
    }

    grpc::Status SearchThreatIndex(grpc::ServerContext* context, const SearchQuery* request,
                                   SearchResponse* reply) override {
        
        std::vector<float> query_vec(request->query_vector().begin(), request->query_vector().end());
        
        auto results = faiss_index_->search(query_vec, request->top_k());
        
        for (const auto& res : results) {
            auto* candidate = reply->add_candidates();
            candidate->set_source_id(std::to_string(res.id)); // Mapping ID to string for demo
            candidate->set_distance(res.distance);
        }
        
        return grpc::Status::OK;
    }
};

void run_grpc_server(const std::string& server_address, 
                     std::shared_ptr<Embedder> emb, 
                     std::shared_ptr<FaissIndexManager> idx) {
                         
    VectorComputeServiceImpl service(emb, idx);
    grpc::ServerBuilder builder;
    
    builder.AddListeningPort(server_address, grpc::InsecureServerCredentials());
    builder.RegisterService(&service);
    
    std::unique_ptr<grpc::Server> server(builder.BuildAndStart());
    std::cout << "🚀 ThreatAtlas C++ gRPC Server listening on " << server_address << std::endl;
    
    server->Wait();
}

} // namespace threatatlas
